### PR TITLE
aniketsingh98571

### PR DESCRIPTION
**Pull request by aniketsingh98571**

### CODE REVIEW

**Comment by aryasoni98** [comment]
Recheck your PR . Your Profile Image and Name , College Name not showing .

**Comment by aniketsingh98571** [comment]
In my branch all the contents are visible,although I have changed the image link. Have a check

**Comment by aniketsingh98571** [comment]
#6 [pic](https://github.com/aniketsingh98571/Hacktoberfest2020/blob/aniketsingh98571/static/images/aniketsingh98571.jpg)
(readme)[https://github.com/aniketsingh98571/Hacktoberfest2020/blob/aniketsingh98571/content/participant/aniketsingh98571.md]

**Comment by aniketsingh98571** [comment]
Now check my file I have made changes #6

**Pull request merged**
