### PR TITLE
Added Profile Information

### PR DESCRIPTION
**Pull request by xdega**
Added my profile information to the yearbook!

### CODE REVIEW

**Comment by reha45** [comment]
Can you please help I tried multiple times but every time my files fail....

**Comment by xdega** [comment]
@reha45 Do you have a link to your pull request?

**Comment by reha45** [comment]
@xdega  yeah i do 
 https://github.com/reha45/Hacktoberfest2020/pull/new/new-user

**Comment by xdega** [comment]
@reha45 Sorry about the delay. Did you push your local changes to the remote branch? Because the pull request has no changes.

**Comment by reha45** [comment]
I resolved the issue, thank you for your help!

**Pull request closed without merging**
