### PR TITLE
Added new profile

### PR DESCRIPTION
**Pull request by rampotter10**
Please merge my pull request

### CODE REVIEW

**Comment by rampotter10** [comment]
#1958

**Comment by rampotter10** [comment]
The PR is showing invalid by Hacktoberfest 2020 team. Why??

**Comment by rampotter10** [comment]
Merge my PR

**Review by aryasoni98 — CHANGES_REQUESTED** [review]
**Note: This is an auto generated comment!** 
Please read the README.md file carefully before making any changes. 
Also, make the changes in your PR according to the below review: 

Please add the `.md` file and your image.

**Pull request closed without merging**
