### PR TITLE
udpate participant profile

### PR DESCRIPTION
**Pull request by phuocquach**

### CODE REVIEW

**Comment by phuocquach** [comment]
@Dishebh could you add topic Hacktoberfest for this repository to join this event ?

**Comment by Dishebh** [comment]
@phuocquach, it is added :)

**Comment by phuocquach** [comment]
> @phuocquach, it is added :)

I still got this on my profile: 
Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

**Comment by phuocquach** [comment]
I close this pull request, hope that we can create other repository complying to Hacktoberfest and join it again.

**Pull request closed without merging**
